Added section for past events. Added Berlin code of conduct. Added De…
Harriethw/queer-tech-bristol pull request #14
Opened 2022-11-26 18:36 UTC by Evie-Skinner18

…cember event to top

Solves #3 and #10 
Adds December event to the site

2022-11-28 13:55 UTC, Harriethw requested changes
thanks so much Evie, can't wait to jingle some bells with you! just had a few comments :) 

The styling on the past events looks a bit off for the second event so think something has been overwritten or lost there 
![Screenshot 2022-11-28 at 13 51 02](https://user-images.githubusercontent.com/16647486/204294097-415df62f-1960-41e1-80b8-2322711856a8.png)

Alsooo this is a small thing and shouldn't stop merging but while I'm here - I wondered if you'd seen the GDS styleguide for commits? One thing they suggest is writing commit messages in present tense as this matches commands generated by stuff like `git merge` (and keeps them shorter!)  https://github.com/alphagov/styleguides/blob/master/git.md#example-1

2022-11-28 13:55 UTC, Harriethw commented on index.html
> +        <section class="past-events">
it looks like the `past-events` and `current-events` classes aren't being used, did you mean to add some styling to them or did you mean them to be more semantic? If they are semantic or for accessibility, I think something like an `aria-label` or `aria-labelledby` tag makes more sense https://www.w3.org/WAI/GL/wiki/Using_HTML5_section_element 

If you *did* want to add styles, [please can we use BEM naming guidelines](https://getbem.com/introduction/) for css? so something like `events__past` maybe?

2022-11-28 13:55 UTC, Harriethw commented on index.html
> +              <div class="events__description">
I think this `div` needs to be closed after line 106

2022-12-02 17:35 UTC, Evie-Skinner18 commented
Thanks for the tips Hazzer @Harriethw I've addressed your feedback

2022-12-02 18:06 UTC, Harriethw approved these changes

2022-12-02 18:06 UTC, merged